language: php
php:
- '7.1'
- '7.2'
before_script:
- composer install --no-interaction
- wget https://scrutinizer-ci.com/ocular.phar
script:
- "./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover"
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
- composer check
